/**
 * ============================================================================
 * TOKEN COMPILER (build-tokens.js) — Precentor
 * ============================================================================
 * Reads precentor-tokens.json (the single source of truth for colour, type,
 * space, layout, font, and transition decisions) and generates
 * static/src/global/variables.css.
 *
 * DO NOT hand-edit variables.css — it is regenerated every time this runs.
 * Edit precentor-tokens.json instead, then:
 *
 *   node build-tokens.js
 *
 * No npm dependencies required — only Node's built-in fs/path modules.
 *
 * Resolution rules (simpler than a typical alias-resolving compiler,
 * because precentor-tokens.json already writes alias values as full
 * var(--colors-neutral-0) strings directly, rather than a "{ref}"
 * shorthand needing separate resolution):
 *  - colors:      each entry becomes --colors-{key}: {value}; as-is,
 *                  whether {value} is a literal hex or an already-formed
 *                  var(...) reference.
 *  - typography:  step keys become --typography-{key} (e.g. step-0).
 *  - spacing:     each key becomes --spacing-{key}.
 *  - layout:      each key becomes --layout-{key}.
 *  - fonts:       each key becomes --fonts-{key}.
 *  - transitions: each key becomes --transitions-{key}.
 *  - Any key starting with "_" (at any depth) is documentation and is
 *    skipped entirely.
 *
 * Dark mode: 'colorsDark' holds only the tokens that differ from
 * 'colors' (same key names, different values). Those overrides are
 * emitted into TWO places:
 *  1. @media (prefers-color-scheme: dark) { :root:not([data-theme]) {} }
 *     — automatic, only when the user hasn't made a manual choice.
 *  2. :root[data-theme="dark"] {}
 *     — explicit, set by the theme toggle and remembered in
 *       localStorage, wins regardless of the OS setting.
 * ============================================================================
 */

const fs = require("fs");
const path = require("path");

const TOKENS_PATH = path.join(__dirname, "precentor-tokens.json");
const OUTPUT_PATH = path.join(
  __dirname,
  "static",
  "src",
  "global",
  "variables.css",
);

function isDocKey(key) {
  return key.startsWith("_");
}

function compileSection(sectionName, prefix) {
  const lines = [];
  Object.entries(sectionName).forEach(([key, value]) => {
    if (isDocKey(key)) return;
    lines.push(`  --${prefix}-${key}: ${value};`);
  });
  return lines;
}

function build() {
  const raw = fs.readFileSync(TOKENS_PATH, "utf8");
  const tokens = JSON.parse(raw);

  const sections = [
    { title: "COLOUR", lines: compileSection(tokens.colors || {}, "colors") },
    {
      title: "TYPOGRAPHY",
      lines: compileSection(tokens.typography || {}, "typography"),
    },
    {
      title: "SPACING",
      lines: compileSection(tokens.spacing || {}, "spacing"),
    },
    { title: "LAYOUT", lines: compileSection(tokens.layout || {}, "layout") },
    { title: "FONTS", lines: compileSection(tokens.fonts || {}, "fonts") },
    {
      title: "TRANSITIONS",
      lines: compileSection(tokens.transitions || {}, "transitions"),
    },
  ];

  const body = sections
    .map(
      (section) =>
        `  /* -- ${section.title} ${"-".repeat(Math.max(0, 68 - section.title.length))} */\n` +
        section.lines.join("\n"),
    )
    .join("\n\n");

  // Dark mode overrides: same --colors-{key} names as the light section
  // above, different values, reused verbatim in both the automatic and
  // explicit-override blocks below.
  const darkLines = compileSection(tokens.colorsDark || {}, "colors");
  const darkBody = darkLines.join("\n");

  const output =
    `/**\n` +
    ` * AUTO-GENERATED by build-tokens.js from precentor-tokens.json.\n` +
    ` * Do not edit this file directly — your changes will be overwritten.\n` +
    ` */\n\n` +
    `:root {\n${body}\n}\n\n` +
    `/* Automatic dark mode — only when no manual theme choice has been made */\n` +
    `@media (prefers-color-scheme: dark) {\n` +
    `  :root:not([data-theme]) {\n${darkBody}\n  }\n` +
    `}\n\n` +
    `/* Explicit manual override — set by the theme toggle, wins regardless of OS setting */\n` +
    `:root[data-theme="dark"] {\n${darkBody}\n}\n`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, "utf8");

  console.log(`[build-tokens] wrote ${path.relative(__dirname, OUTPUT_PATH)}`);
}

build();
