# Generated by Django 6.0.7 on 2026-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(blank=True, max_length=200)),
                ('crest_image', models.ImageField(blank=True, upload_to='site_config/')),
                ('house_accent_colour', models.CharField(default='#8b1a2b', max_length=7)),
                ('layout_style', models.CharField(choices=[('columns', 'Newspaper columns'), ('simple', 'Simple single column')], default='columns', max_length=20)),
                ('show_hymns_psalm', models.BooleanField(default=True)),
            ],
        ),
    ]
