# Generated by Django 6.0.7 on 2026-07-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0003_liturgicalseason_usetype_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_occasions',
            field=models.ManyToManyField(blank=True, related_name='also_relevant_services', to='ordo.liturgicaloccasion'),
        ),
        migrations.AddField(
            model_name='service',
            name='calendar_use',
            field=models.CharField(blank=True, choices=[('current', 'Current (Common Worship / Novus Ordo)'), ('historic', 'Historic (Book of Common Prayer / Extraordinary Form)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tradition',
            field=models.CharField(blank=True, choices=[('catholic', 'Catholic'), ('cofe', 'Church of England')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='calendar_use',
            field=models.CharField(choices=[('current', 'Current (Common Worship / Novus Ordo)'), ('historic', 'Historic (Book of Common Prayer / Extraordinary Form)')], default='current', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='tradition',
            field=models.CharField(choices=[('catholic', 'Catholic'), ('cofe', 'Church of England')], default='cofe', max_length=20),
            preserve_default=False,
        ),
    ]
