# Generated by Django 6.0.7 on 2026-07-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_service_additional_occasions_service_calendar_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hymns',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='psalm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
