# Generated by Django 6.0.7 on 2026-07-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_service_hymns_service_psalm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=200)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='planning.term')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
