# Generated by Django 6.0.7 on 2026-07-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tradition', models.CharField(choices=[('catholic', 'Catholic'), ('cofe', 'Church of England')], max_length=20)),
                ('is_moveable', models.BooleanField(default=False)),
                ('fixed_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fixed_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('easter_offset_days', models.IntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['tradition', 'name'],
            },
        ),
    ]
