# Generated by Django 6.0.7 on 2026-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liturgicaloccasion',
            name='colour',
            field=models.CharField(blank=True, choices=[('violet', 'Violet'), ('red', 'Red'), ('green', 'Green'), ('white', 'White/Gold'), ('rose', 'Rose')], max_length=20),
        ),
    ]
