# Generated by Django 6.0.7 on 2026-07-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0002_alter_liturgicaloccasion_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tradition', models.CharField(choices=[('catholic', 'Catholic'), ('cofe', 'Church of England')], max_length=20)),
            ],
            options={
                'ordering': ['tradition', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='liturgicaloccasion',
            name='calendar_use',
            field=models.CharField(choices=[('current', 'Current (Common Worship / Novus Ordo)'), ('historic', 'Historic (Book of Common Prayer / Extraordinary Form)')], default='current', max_length=20),
        ),
        migrations.AddField(
            model_name='liturgicaloccasion',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occasions', to='ordo.liturgicalseason'),
        ),
    ]
